M :eyes:

diff --git a/local_bin/myaria2 b/local_bin/myaria2
--- a/local_bin/myaria2
+++ b/local_bin/myaria2
@@ -1,14 +1,17 @@
 #!/usr/bin/env bash
-# Github: https://github.com/Karmenzind/MyConfig/tree/master/others/aria2
+# Github: https://github.com/Karmenzind/dotfiles-and-scripts/tree/master/others/aria2
 # a script to manage aria2
 
 download_dir=${HOME}/Downloads/aria2
+
+![[ -d "$download_dir" ]] && mkdir -p $download_dir && echo "Created $download_dir"
 
 # -----------------------------------------------------------------------------
 # /* custom variables */
 
 # follow your aria2 config
-log_path=${HOME}/Downloads/aria2/_log
+log_path=/tmp/_aria2.log
+
 
 # url to fetch bt-tracker list
 # if your have no idea what it is
@@ -20,6 +23,8 @@ update_interval_hours=4
 # to save your trackerlist
 # no need to change
 config_dir=${HOME}/.config/aria2 # trackerlist
+
+![[ -d "$config_dir" ]] && mkdir -p $config_dir && echo "Created $config_dir"
 
 # \ Leave open_browser/save_history to 0 
 # \ if you don't need functions as follows
@@ -33,6 +38,7 @@ browser=chromium
 # move log file to specific dir when restart
 save_history=0
 history_dir=${HOME}/Downloads/aria2/logs # leave it to '' if you don't need it
+![[ -d "$history_dir" ]] && mkdir -p $history_dir && echo "Created $history_dir"
 
 # aria2c running paramters. See aria2c's man page
 aria2c_params="--rpc-listen-all --enable-rpc $@"
@@ -103,14 +109,19 @@ start() {
         aria2c_params="--rpc-listen-all --enable-rpc $@"
         [[ -n ${trackers} ]] && aria2c_params="--bt-tracker=$trackers $aria2c_params"
         echo '[PARAMETERS]' $aria2c_params
-        aria2c $aria2c_params
+        if aria2c $aria2c_params; then
+            echo "Started"
+        else
+            echo "Starting failed. Return code $?"
+            log
+        fi
         psinfo
     fi
 }
 
 log() {
     echo -e  '\nLOG:'
-    tail $log_path $1
+    tail $log_path $1 
 }
 
 # return 1: need update
